name: Security

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
      - name: npm audit (fail-soft)
        run: npm audit --omit=dev || true

  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Gitleaks scan (fail-soft)
        uses: gitleaks/gitleaks-action@c8fd8608c4d4f9f7b5a2a42b1e9796c9b876d2fe
        continue-on-error: true
